// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NameSurnameEF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameSurnameEF));
        
        string IMigrationMetadata.Id
        {
            get { return "201412282102439_NameSurnameEF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
